[package]
name = "monotrail"
version = "0.1.0"
description = "This proof of concept shows how to use python packages without virtualenvs"
edition = "2021"
readme = "Readme.md"

[workspace]
members = [
    "install-wheel-rs",
    "monotrail-utils",
]

[lib]
crate-type = ["rlib", "cdylib"]
name = "monotrail"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { version = "4.4.4", features = ["derive"] }
cpufeatures = "0.2.9"
dirs = "5.0.1"
fs-err = { workspace = true }
fs2 = { workspace = true }
git2 = "0.18.1"
indicatif = "0.17.7"
install-wheel-rs = { version = "0.0.3", path = "install-wheel-rs" }
libc = "0.2.148"
libloading = "0.8.0"
# For the zig build
libz-sys = { version = "1.1.12", features = ["static"] }
monotrail-utils = { version = "0.0.1", path = "monotrail-utils" }
nix = { version = "0.27.1", features = ["process"] }
pep440_rs = "0.3.11"
pep508_rs = { workspace = true, features = ["serde"] }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py37"], optional = true }
rayon = "1.8.0"
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = "0.4.40"
target-lexicon = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
unscanny = { workspace = true }
ureq = { version = "2.7.1", features = ["json"] }
walkdir = { workspace = true }
widestring = "1.0.2"
zstd = "0.12.4"

[workspace.dependencies]
anyhow = "1.0.75"
base64 = "0.21.4"
fs-err = "2.9.0"
fs2 = "0.4.3"
indoc = "2.0.4"
logtest = "2.0.0"
mockito = "1.2.0"
pep508_rs = { version = "0.2.1", features = ["serde"] }
pyo3 = { version = "0.19.2", features = ["extension-module", "abi3-py37"] }
regex = "1.9.5"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.7"
target-lexicon = "0.12.11"
tempfile = "3.8.0"
thiserror = "1.0.48"
toml = "0.8.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
unscanny = "0.1.0"
walkdir = "2.4.0"
which = "4.4.2"

[features]
default = ["vendored"]
python_bindings = ["pyo3", "install-wheel-rs/python_bindings"]
vendored = ["git2/vendored-openssl", "git2/vendored-libgit2"]

# zip implementation
[profile.dev.package.adler]
opt-level = 3

# https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.perf]
inherits = "release"
debug = 1

[dev-dependencies]
indoc = { workspace = true }
logtest = { workspace = true }
mockito = { workspace = true }
tempfile = { workspace = true }
which = { workspace = true }
